create table if not exists public.mirage_audit_logs (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.mirage_workspaces(id) on delete cascade,
  action text not null default 'update',
  summary text not null,
  sections text[] not null default '{}'::text[],
  staff_id uuid references auth.users(id),
  staff_email text,
  staff_name text,
  staff_avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.mirage_audit_logs
  add column if not exists staff_avatar_url text;

create index if not exists mirage_audit_logs_workspace_created_idx
  on public.mirage_audit_logs (workspace_id, created_at desc);

alter table public.mirage_audit_logs enable row level security;

drop policy if exists "Staff can read Mirage audit logs" on public.mirage_audit_logs;
create policy "Staff can read Mirage audit logs"
  on public.mirage_audit_logs
  for select
  to authenticated
  using (true);

drop policy if exists "Staff can create Mirage audit logs" on public.mirage_audit_logs;
create policy "Staff can create Mirage audit logs"
  on public.mirage_audit_logs
  for insert
  to authenticated
  with check (auth.uid() = staff_id);
